version: '3'

services:
  php:
    image: php:8.3-fpm
    volumes:
      - .:/var/www/html
  web:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8888:80